name: Generate Marketing Screenshots

on: workflow_dispatch

jobs:
  generate-marketing-snapshots:
    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - name: Switch Xcode version
      run: sudo xcode-select -s "/Applications/Xcode_12.3.app"

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

    - name: Scripts Marketing Screenshots Generation
      run: swift run --package-path Scripts

    - uses: actions/upload-artifact@v2
      with:
        name: marketing-screenshots
        path: '.ExportedScreenshots/*'
        retention-days: 5

