name: Xcode Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-ios:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Linter
      run: swiftlint

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Create iPhone SE Simulator
      run: xcrun simctl create "iPhone SE (1st generation)" "iPhone SE (1st generation)"

    - name: Xcode test on iPhone SE
      run: xcodebuild clean test -scheme "MemoArt (iOS)" -destination 'platform=iOS Simulator,name=iPhone SE (1st generation)'
  build-macos:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Xcode test on Mac
      run: xcodebuild clean test -scheme "MemoArt (macOS)"
